# Generated by Django 5.2 on 2025-05-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loss',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='loss',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
