# Generated by Django 5.2 on 2025-05-06 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0003_category_is_subcategory_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='is_subcategory',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='added_date',
        ),
        migrations.AlterField(
            model_name='loss',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dlc_app.category'),
        ),
        migrations.AlterField(
            model_name='loss',
            name='loss_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='loss',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dlc_app.product'),
        ),
        migrations.AlterField(
            model_name='loss',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='loss',
            name='reason',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=50),
        ),
    ]
