# Generated by Django 5.2 on 2025-05-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlc_app', '0004_remove_category_is_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loss',
            name='product_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
